
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: MSBuild@1
  inputs:
    solution: 'ShapeRecognizer.sln'
    platform: 'Any CPU'
    configuration: 'Release'
    maximumCpuCount: true
    restoreNugetPackages: true
